test
NGO-AQE-Project/NGO-AQE-Project pull request #2
Opened 2024-07-15 13:03 UTC by marinatea

https://app.clickup.com/t/86951rz6f

2024-07-15 14:35 UTC, weswojciech requested changes

2024-07-15 14:35 UTC, weswojciech commented on src/styles/fonts.scss
> +  font-family: PoppinsSemobold, sans-serif;
Semibold instead of semobold

2024-07-15 14:35 UTC, weswojciech commented on src/styles/fonts.scss
> +  font-family: PoppinsSemobold, sans-serif;
Semibold instead of semobold

2024-07-15 14:35 UTC, weswojciech commented on src/styles/fonts.scss
> +  font-family: PoppinsSemobold, sans-serif;
Semibold instead of semobold

2024-07-15 14:35 UTC, weswojciech commented on src/styles/fonts.scss
> +  font-family: PoppinsSemobold, sans-serif;
Semibold instead of semobold

2024-07-15 14:35 UTC, weswojciech commented on src/App.scss
> +
I don't see `box-sizing: border-box` nowhere, it might be required

2024-07-15 14:47 UTC, danon321 commented on src/App.scss
> +}
Jak to wszystko są resety stwórz specjalny plik reset.scss do tego. Bo tak to sie robi smietnik

2024-07-15 14:47 UTC, danon321 commented on src/styles/main.css
> +/*
czemu tu mamy plik .css a nie .scss?

2024-07-15 14:48 UTC, danon321 commented
Nie nazywaj commitów i PR "test" bo pozniej nie wiadomo o co w nich chodziło

2024-07-15 18:51 UTC, JustinNowoczek commented on src/styles/mediaQueries.module.scss
> +@mixin phone {
This does not seem too useful

2024-07-15 18:54 UTC, JustinNowoczek commented on public/index.html
> +  <title>Document</title>
Could use a more descriptive title

2024-07-16 09:23 UTC, weswojciech approved these changes

2024-07-16 09:23 UTC, weswojciech approved these changes

2024-07-16 10:09 UTC, merged